name: nosso_cafofo
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.1.1
  firebase_auth: ^4.0.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1

  google_sign_in: ^5.4.2
  
  permission_handler: ^10.2.0
  font_awesome_flutter: ^10.2.1
  image_picker: ^0.8.6
  path: ^1.8.2
  file_picker: ^5.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Launcher Icon
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logocafofo.png" # ADD a Launcher Icon image
  min_sdk_android: 21 # android min sdk min:16, default 21
  

  
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/SplashScreen/SplashScreenIcon.png 
    - assets/images/Login/Icone.png
    - assets/images/Login/googleicon.png
    - assets/images/Login/facebook.png
    - assets/images/Login/twittericon.png
  #add Splash screen Image
  

